=== jcolson/meganslaw/src/java/sandbox/megan.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://megan.blackntan.com/xsd/megan.xsd" xmlns="http://megan.blackntan.com/xsd/megan.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="megan">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="baddy" maxOccurs="unbounded" type="ct_Baddy"/>
      </xs:sequence>
      <xs:attribute name="lat" use="required" type="xs:decimal"/>
      <xs:attribute name="long" use="required" type="xs:decimal"/>
      <xs:attribute name="zip" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="ct_Baddy">
      <xs:sequence>
        <xs:element name="img" type="ct_Img"/>
        <xs:element name="name" type="ct_Name"/>
        <xs:element minOccurs="0" name="whitepages" type="ct_Whitepages"/>
        <xs:element name="geocode" type="ct_Geocode"/>
      </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ct_Img">
      <xs:attribute name="src" use="required" type="xs:anyURI"/>
  </xs:complexType>
  <xs:complexType name="ct_Whitepages">
      <xs:sequence>
        <xs:element name="name" type="ct_Name"/>
        <xs:element name="address" type="ct_Address"/>
      </xs:sequence>
    </xs:complexType>
  <xs:complexType name="ct_Address">
      <xs:attribute name="city" use="required" type="xs:NCName"/>
      <xs:attribute name="phone" use="required"/>
      <xs:attribute name="state" use="required" type="xs:NCName"/>
      <xs:attribute name="street" use="required"/>
      <xs:attribute name="zip" use="required" type="xs:integer"/>
    </xs:complexType>
  <xs:complexType name="ct_Geocode">
      <xs:attribute name="lat" use="required" type="xs:decimal"/>
      <xs:attribute name="long" use="required" type="xs:decimal"/>
    </xs:complexType>
  <xs:complexType name="ct_Name">
      <xs:attribute name="first" type="xs:NCName"/>
      <xs:attribute name="full" use="required"/>
      <xs:attribute name="last" type="xs:NCName"/>
    </xs:complexType>
</xs:schema>

=== jcolson/meganslaw/doc/megan_18017.xml
<?xml version="1.0" encoding="UTF-8"?>
<megan xmlns="http://megan.blackntan.com/xsd/megan.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://megan.blackntan.com/xsd/megan.xsd megan.xsd" zip="18017"
    lat="40.65168" long="-75.35823">
    <baddy>
        <img src="http://www.pameganslaw.state.pa.us/image.aspx?Text=beejdcff"/>
        <name first="MARK" last="DORRAH" full="MARK ALFRED DORRAH"/>
        <geocode lat="40.65168" long="-75.35823"/>
    </baddy>
    <baddy>
        <img src="http://www.pameganslaw.state.pa.us/image.aspx?Text=dadahbfb"/>
        <name first="JOSHUA" last="MOORE" full="JOSHUA MOORE"/>
        <whitepages>
            <name full="J Moore"/>
            <address street="2041 Westfield Ter" city="Bethlehem" state="PA" zip="18017" phone="(610) 317-9695"/>
        </whitepages>
        <geocode lat="40.640466" long="-75.404398"/>
    </baddy>
    <baddy>
        <img src="http://www.pameganslaw.state.pa.us/image.aspx?Text=cfefddjf"/>
        <name first="ARTHUR" last="SUSSMEIER" full="ARTHUR ALBERT SUSSMEIER JR"/>
        <geocode lat="40.65168" long="-75.35823"/>
    </baddy>
    <baddy>
        <img src="http://www.pameganslaw.state.pa.us/image.aspx?Text=bfdcihfe"/>
        <name first="CHRISTINO" last="CASTRO" full="CHRISTINO CASTRO"/>
        <geocode lat="40.65168" long="-75.35823"/>
    </baddy>
    <baddy>
        <img src="http://www.pameganslaw.state.pa.us/image.aspx?Text=cedgihec"/>
        <name first="MARK" last="GORDON" full="MARK TAYLOR GORDON"/>
        <geocode lat="40.65168" long="-75.35823"/>
    </baddy>
    <baddy>
        <img src="http://www.pameganslaw.state.pa.us/image.aspx?Text=dcceebag"/>
        <name first="TODD" last="ISSERMOYER" full="TODD AARON ISSERMOYER"/>
        <geocode lat="40.65168" long="-75.35823"/>
    </baddy>
    <baddy>
        <img src="http://www.pameganslaw.state.pa.us/image.aspx?Text=cgbgecej"/>
        <name first="JOSE" last="JIMENEZ" full="JOSE JULIAN JIMENEZ"/>
        <whitepages>
            <name full="Jose Jimenez"/>
            <address street="1977 Gatewood Ln" city="Bethlehem" state="PA" zip="18017" phone="(610) 419-0910"/>
        </whitepages>
        <geocode lat="40.65168" long="-75.35823"/>
    </baddy>
    <baddy>
        <img src="http://www.pameganslaw.state.pa.us/image.aspx?Text=cfefjeea"/>
        <name first="DOUGLAS" last="KLINGER" full="DOUGLAS ALLEN KLINGER"/>
        <geocode lat="40.65168" long="-75.35823"/>
    </baddy>
    <baddy>
        <img src="http://www.pameganslaw.state.pa.us/image.aspx?Text=cccjcaaf"/>
        <name first="DANIEL" last="LAU" full="DANIEL K LAU"/>
        <geocode lat="40.65168" long="-75.35823"/>
    </baddy>
    <baddy>
        <img src="http://www.pameganslaw.state.pa.us/image.aspx?Text=aiaaajfg"/>
        <name first="ANIBAL" last="MALDONADO" full="ANIBAL RIVERA MALDONADO"/>
        <geocode lat="40.65168" long="-75.35823"/>
    </baddy>
    <baddy>
        <img src="http://www.pameganslaw.state.pa.us/image.aspx?Text=cfhjedfe"/>
        <name first="THANG" last="NGUYEN" full="THANG NGUYEN"/>
        <whitepages>
            <name full="T Nguyen"/>
            <address street="403 E Macada Rd" city="Bethlehem" state="PA" zip="18017" phone="(610) 867-3736"/>
        </whitepages>
        <geocode lat="40.655153" long="-75.371598"/>
    </baddy>
    <baddy>
        <img src="http://www.pameganslaw.state.pa.us/image.aspx?Text=ccgejdcj"/>
        <name first="KICO" last="OCASIO" full="KICO OCASIO"/>
        <geocode lat="40.65168" long="-75.35823"/>
    </baddy>
    <baddy>
        <img src="http://www.pameganslaw.state.pa.us/image.aspx?Text=dcjghdfd"/>
        <name first="JONATHAN" last="RITZ" full="JONATHAN ALLEN RITZ"/>
        <geocode lat="40.65168" long="-75.35823"/>
    </baddy>
    <baddy>
        <img src="http://www.pameganslaw.state.pa.us/image.aspx?Text=daceaibc"/>
        <name first="THADDEUS" last="VASKAS" full="THADDEUS C VASKAS"/>
        <geocode lat="40.65168" long="-75.35823"/>
    </baddy>
    <baddy>
        <img src="http://www.pameganslaw.state.pa.us/image.aspx?Text=bedfaabc"/>
        <name first="RICHARD" last="WEITKAMP" full="RICHARD A WEITKAMP"/>
        <geocode lat="40.65168" long="-75.35823"/>
    </baddy>
    <baddy>
        <img src="http://www.pameganslaw.state.pa.us/image.aspx?Text=cicihghe"/>
        <name first="GEORGE" last="HESS" full="GEORGE DENNIS HESS"/>
        <whitepages>
            <name full="George D Hess"/>
            <address street="212 Juniata St" city="Freemansburg" state="PA" zip="18017" phone="(610) 691-8164"/>
        </whitepages>
        <geocode lat="40.624554" long="-75.342282"/>
    </baddy>
    <baddy>
        <img src="http://www.pameganslaw.state.pa.us/image.aspx?Text=cfeigbii"/>
        <name first="DENNIS" last="HORVATH" full="DENNIS LEE HORVATH JR"/>
        <whitepages>
            <name full="Dennis Horvath"/>
            <address street="2161 West Blvd" city="Bethlehem" state="PA" zip="18017" phone="(610) 866-8789"/>
        </whitepages>
        <geocode lat="40.643629" long="-75.353009"/>
    </baddy>
</megan>
